// Malaysian Mock Data for DataSync AI

export const recentActivity = [
  {
    id: "1",
    fileName: "CIMB_Overdue_Jan2024.xlsx",
    source: "email" as const,
    bank: "CIMB",
    status: "completed" as const,
    rows: 1247,
    timestamp: "2 mins ago",
  },
  {
    id: "2",
    fileName: "Maybank_Collections_Q4.xlsx",
    source: "sftp" as const,
    bank: "Maybank",
    status: "processing" as const,
    rows: 892,
    timestamp: "5 mins ago",
  },
  {
    id: "3",
    fileName: "Manual_Upload_RHB.xlsx",
    source: "upload" as const,
    bank: "RHB",
    status: "completed" as const,
    rows: 456,
    timestamp: "12 mins ago",
  },
  {
    id: "4",
    fileName: "CIMB_NPL_Dec2023.zip",
    source: "email" as const,
    bank: "CIMB",
    status: "failed" as const,
    rows: 0,
    timestamp: "15 mins ago",
    error: "Incorrect password",
  },
  {
    id: "5",
    fileName: "Maybank_Batch_002.xlsx",
    source: "sftp" as const,
    bank: "Maybank",
    status: "completed" as const,
    rows: 2103,
    timestamp: "1 hour ago",
  },
];

export const standardizedData = [
  {
    id: "1",
    sourceFile: "CIMB_Overdue_Jan2024.xlsx",
    bank: "CIMB",
    clientName: "Ahmad Bin Ali",
    accountNo: "7012345678",
    dueAmount: 15420.50,
    dueDate: "2024-01-15",
    status: "valid" as const,
  },
  {
    id: "2",
    sourceFile: "CIMB_Overdue_Jan2024.xlsx",
    bank: "CIMB",
    clientName: "Siti Sarah Binti Abdullah",
    accountNo: "7098765432",
    dueAmount: 8750.00,
    dueDate: "2024-01-20",
    status: "valid" as const,
  },
  {
    id: "3",
    sourceFile: "Maybank_Collections_Q4.xlsx",
    bank: "Maybank",
    clientName: "Tan Wei Ming",
    accountNo: "1142789456",
    dueAmount: 23100.75,
    dueDate: "2024-01-10",
    status: "valid" as const,
  },
  {
    id: "4",
    sourceFile: "Maybank_Collections_Q4.xlsx",
    bank: "Maybank",
    clientName: "Rajesh A/L Kumar",
    accountNo: "1145678901",
    dueAmount: 5890.25,
    dueDate: "2024-01-25",
    status: "invalid" as const,
    error: "Missing account type",
  },
  {
    id: "5",
    sourceFile: "Manual_Upload_RHB.xlsx",
    bank: "RHB",
    clientName: "Nurul Izzah Binti Hassan",
    accountNo: "2156789012",
    dueAmount: 12340.00,
    dueDate: "2024-01-18",
    status: "valid" as const,
  },
  {
    id: "6",
    sourceFile: "Manual_Upload_RHB.xlsx",
    bank: "RHB",
    clientName: "Lee Chong Wei",
    accountNo: "2198765432",
    dueAmount: 45670.80,
    dueDate: "2024-01-22",
    status: "valid" as const,
  },
  {
    id: "7",
    sourceFile: "CIMB_Overdue_Jan2024.xlsx",
    bank: "CIMB",
    clientName: "Mohammad Faiz Bin Yusof",
    accountNo: "7034567890",
    dueAmount: 9200.00,
    dueDate: "2024-01-28",
    status: "valid" as const,
  },
  {
    id: "8",
    sourceFile: "Maybank_Collections_Q4.xlsx",
    bank: "Maybank",
    clientName: "Priya A/P Subramaniam",
    accountNo: "1178901234",
    dueAmount: 18500.50,
    dueDate: "2024-01-12",
    status: "valid" as const,
  },
];

export const sftpServers = [
  {
    id: "1",
    bank: "CIMB",
    host: "sftp.cimb.com.my",
    port: 22,
    status: "connected" as const,
    lastSync: "2 mins ago",
  },
  {
    id: "2",
    bank: "Maybank",
    host: "secure.maybank2u.com.my",
    port: 22,
    status: "connected" as const,
    lastSync: "5 mins ago",
  },
  {
    id: "3",
    bank: "RHB",
    host: "sftp.rhbgroup.com",
    port: 2222,
    status: "disconnected" as const,
    lastSync: "3 hours ago",
  },
];

export const decryptionPatterns = [
  {
    id: "1",
    bank: "CIMB",
    pattern: "AgencyCode + DDMMYYYY",
    example: "ABC01152024",
    status: "active" as const,
  },
  {
    id: "2",
    bank: "Maybank",
    pattern: "Fixed PIN",
    example: "MBB@2024",
    status: "active" as const,
  },
  {
    id: "3",
    bank: "RHB",
    pattern: "AccountID + Month",
    example: "RHB789JAN",
    status: "testing" as const,
  },
];

export const aiMappings = [
  { input: "Acc_No", output: "account_number", confidence: 98 },
  { input: "Cust_Name", output: "client_name", confidence: 95 },
  { input: "O/S Amt", output: "due_amount", confidence: 92 },
  { input: "Due_Dt", output: "due_date", confidence: 97 },
  { input: "IC_No", output: "ic_number", confidence: 99 },
  { input: "Phone", output: "contact_number", confidence: 94 },
];

export const auditLogs = [
  {
    id: "1",
    timestamp: "2024-01-15 14:32:15",
    level: "error" as const,
    message: "Failed to unzip Maybank_01.rar - Incorrect Password",
    source: "Decryption Engine",
  },
  {
    id: "2",
    timestamp: "2024-01-15 14:30:45",
    level: "success" as const,
    message: "Successfully processed CIMB_Overdue_Jan2024.xlsx - 1247 rows",
    source: "AI Mapper",
  },
  {
    id: "3",
    timestamp: "2024-01-15 14:28:00",
    level: "warning" as const,
    message: "Column 'Addr' not mapped - using default NULL",
    source: "AI Mapper",
  },
  {
    id: "4",
    timestamp: "2024-01-15 14:25:30",
    level: "info" as const,
    message: "Email agent polling imap.gmail.com - 3 new attachments",
    source: "Email Listener",
  },
  {
    id: "5",
    timestamp: "2024-01-15 14:20:00",
    level: "success" as const,
    message: "SFTP sync completed - Maybank server",
    source: "SFTP Connector",
  },
];

export const subscriptionPlans = [
  {
    id: "starter",
    name: "Starter",
    price: 99,
    currency: "RM",
    features: [
      "500 Files / Month",
      "Email Support",
      "Basic AI Mapping",
      "Email Integration Only",
    ],
    limitations: ["No SFTP Support", "Standard Processing Speed"],
  },
  {
    id: "business",
    name: "Business",
    price: 299,
    currency: "RM",
    features: [
      "Unlimited Files",
      "Priority Support",
      "Advanced AI Mapping",
      "Email + SFTP Integration",
      "Custom Decryption Rules",
      "API Access",
    ],
    recommended: true,
  },
  {
    id: "enterprise",
    name: "Enterprise",
    price: null,
    currency: "RM",
    features: [
      "Everything in Business",
      "Dedicated Account Manager",
      "Custom Integrations",
      "On-premise Deployment",
      "SLA Guarantee",
    ],
  },
];

export const dashboardStats = {
  filesToday: 47,
  filesMonth: 1284,
  rowsStandardized: 156789,
  manHoursSaved: 120,
  successRate: 98.5,
  activeAgents: 2,
};
